#!/bin/bash

export AWS_PROFILE=everest-internal
export TENANT=tenant-b64877cf-78cd-4715-8395-0f12c93e9b34
export USER=kernel_ro

source ${BASH_SOURCE%/*}/../../aws-login.bash $AWS_PROFILE
source ${BASH_SOURCE%/*}/../aws-pghost.bash $AWS_PROFILE $TENANT

export PGUSER=$USER
export PGDATABASE=$TENANT

source ${BASH_SOURCE%/*}/../secrets/kernel-pw.bash
source ${BASH_SOURCE%/*}/../kernel.bash
