#!/bin/bash

export PGHOST=tenant-c99511c6-fc7c-4d0d-b76c-0455ca9a4c10.cluster-cqim8xet1dbv.us-east-1.rds.amazonaws.com
export PGDATABASE=tenant-c99511c6-fc7c-4d0d-b76c-0455ca9a4c10
export PGUSER=kernel

source ${BASH_SOURCE%/*}/../secrets/kernel-pw.bash
source ${BASH_SOURCE%/*}/../kernel.bash
