[font]
size = 13.0
normal = { family = "DejaVuSansM Nerd Font", style = "Regular" }
bold = { family = "DejaVuSansM Nerd Font", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font", style = "Italic" }
bold_italic = { family = "DejaVuSansM Nerd Font", style = "Bold Italic" }

[window]
option_as_alt = "Both"

[keyboard]
bindings = [
    { mods = "Shift|Command", key = "N", action = "CreateNewWindow" },
    # zellij
    { mods = "Command", key = "Q", action = "None" },
    { mods = "Command", key = "W", chars = "\u001Bw" },
    { mods = "Command", key = "D", chars = "\u001Bd" },
    { mods = "Command|Shift", key = "D", chars = "\u001BD" },
    { mods = "Command", key = "T", chars = "\u001Bz" },
    { mods = "Command", key = "C", chars = "\u001Bc" },
    { mods = "Command", key = "Key1", chars = "\u001B1" },
    { mods = "Command", key = "Key2", chars = "\u001B2" },
    { mods = "Command", key = "Key3", chars = "\u001B3" },
    { mods = "Command", key = "Key4", chars = "\u001B4" },
    { mods = "Command", key = "Key5", chars = "\u001B5" },
]
