#!/bin/bash

export AWS_PROFILE=everest-internal
export PGHOST=tenant-1e15fd4c-9694-4107-928d-11cb97422adc.cluster-cqim8xet1dbv.us-east-1.rds.amazonaws.com
export PGUSER=nico@everest-erp.com

export PGDATABASE=$(echo $PGHOST | cut -d '.' -f 1)

source ${BASH_SOURCE%/*}/../aws-pgpassword.bash $AWS_PROFILE
source ${BASH_SOURCE%/*}/../kernel.bash
